name: pylint-examples

on:
  push:
    branches:
      - main
    paths:
      - '*.py'
  pull_request:
    branches:
      - main
    paths:
      - '*.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pylint:
    name: Lint mcd application
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run PyLint 
        run: pylint *.py
